version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot-daniel
      - bot-rafael

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./certbot.conf:/etc/nginx/conf.d/certbot.conf
      - ./certbot-webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --staging -d yourdomain.com -d www.yourdomain.com
    depends_on:
      - nginx

  bot-daniel:
    image: hardrack/personal-ws-bot:latest
    restart: always
    container_name: bot-daniel
    ports:
      - 3000:3000
    volumes:
      - ./bot-volume-daniel:/app/bot_sessions

  bot-rafael:
    image: hardrack/personal-ws-bot:latest
    restart: always
    container_name: bot-rafael
    ports:
      - 3001:3000
    volumes:
      - ./bot-volume-rafael:/app/bot_sessions

networks:
  personal_ws_bots:
